/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthImport } from './routes/_auth'
import { Route as LangIndexImport } from './routes/$lang.index'
import { Route as LangLoginImport } from './routes/$lang.login'
import { Route as AuthInvoicesInvoiceIdImport } from './routes/_auth.invoices.$invoiceId'
import { Route as AuthLangDashboardImport } from './routes/_auth.$lang.dashboard'
import { Route as AuthLangInvoicesIndexImport } from './routes/_auth.$lang.invoices.index'

// Create/Update Routes

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const LangIndexRoute = LangIndexImport.update({
  id: '/$lang/',
  path: '/$lang/',
  getParentRoute: () => rootRoute,
} as any)

const LangLoginRoute = LangLoginImport.update({
  id: '/$lang/login',
  path: '/$lang/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthInvoicesInvoiceIdRoute = AuthInvoicesInvoiceIdImport.update({
  id: '/invoices/$invoiceId',
  path: '/invoices/$invoiceId',
  getParentRoute: () => AuthRoute,
} as any)

const AuthLangDashboardRoute = AuthLangDashboardImport.update({
  id: '/$lang/dashboard',
  path: '/$lang/dashboard',
  getParentRoute: () => AuthRoute,
} as any)

const AuthLangInvoicesIndexRoute = AuthLangInvoicesIndexImport.update({
  id: '/$lang/invoices/',
  path: '/$lang/invoices/',
  getParentRoute: () => AuthRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/$lang/login': {
      id: '/$lang/login'
      path: '/$lang/login'
      fullPath: '/$lang/login'
      preLoaderRoute: typeof LangLoginImport
      parentRoute: typeof rootRoute
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangIndexImport
      parentRoute: typeof rootRoute
    }
    '/_auth/$lang/dashboard': {
      id: '/_auth/$lang/dashboard'
      path: '/$lang/dashboard'
      fullPath: '/$lang/dashboard'
      preLoaderRoute: typeof AuthLangDashboardImport
      parentRoute: typeof AuthImport
    }
    '/_auth/invoices/$invoiceId': {
      id: '/_auth/invoices/$invoiceId'
      path: '/invoices/$invoiceId'
      fullPath: '/invoices/$invoiceId'
      preLoaderRoute: typeof AuthInvoicesInvoiceIdImport
      parentRoute: typeof AuthImport
    }
    '/_auth/$lang/invoices/': {
      id: '/_auth/$lang/invoices/'
      path: '/$lang/invoices'
      fullPath: '/$lang/invoices'
      preLoaderRoute: typeof AuthLangInvoicesIndexImport
      parentRoute: typeof AuthImport
    }
  }
}

// Create and export the route tree

interface AuthRouteChildren {
  AuthLangDashboardRoute: typeof AuthLangDashboardRoute
  AuthInvoicesInvoiceIdRoute: typeof AuthInvoicesInvoiceIdRoute
  AuthLangInvoicesIndexRoute: typeof AuthLangInvoicesIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLangDashboardRoute: AuthLangDashboardRoute,
  AuthInvoicesInvoiceIdRoute: AuthInvoicesInvoiceIdRoute,
  AuthLangInvoicesIndexRoute: AuthLangInvoicesIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof AuthRouteWithChildren
  '/$lang/login': typeof LangLoginRoute
  '/$lang': typeof LangIndexRoute
  '/$lang/dashboard': typeof AuthLangDashboardRoute
  '/invoices/$invoiceId': typeof AuthInvoicesInvoiceIdRoute
  '/$lang/invoices': typeof AuthLangInvoicesIndexRoute
}

export interface FileRoutesByTo {
  '': typeof AuthRouteWithChildren
  '/$lang/login': typeof LangLoginRoute
  '/$lang': typeof LangIndexRoute
  '/$lang/dashboard': typeof AuthLangDashboardRoute
  '/invoices/$invoiceId': typeof AuthInvoicesInvoiceIdRoute
  '/$lang/invoices': typeof AuthLangInvoicesIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_auth': typeof AuthRouteWithChildren
  '/$lang/login': typeof LangLoginRoute
  '/$lang/': typeof LangIndexRoute
  '/_auth/$lang/dashboard': typeof AuthLangDashboardRoute
  '/_auth/invoices/$invoiceId': typeof AuthInvoicesInvoiceIdRoute
  '/_auth/$lang/invoices/': typeof AuthLangInvoicesIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/$lang/login'
    | '/$lang'
    | '/$lang/dashboard'
    | '/invoices/$invoiceId'
    | '/$lang/invoices'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/$lang/login'
    | '/$lang'
    | '/$lang/dashboard'
    | '/invoices/$invoiceId'
    | '/$lang/invoices'
  id:
    | '__root__'
    | '/_auth'
    | '/$lang/login'
    | '/$lang/'
    | '/_auth/$lang/dashboard'
    | '/_auth/invoices/$invoiceId'
    | '/_auth/$lang/invoices/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LangLoginRoute: typeof LangLoginRoute
  LangIndexRoute: typeof LangIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LangLoginRoute: LangLoginRoute,
  LangIndexRoute: LangIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_auth",
        "/$lang/login",
        "/$lang/"
      ]
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/$lang/dashboard",
        "/_auth/invoices/$invoiceId",
        "/_auth/$lang/invoices/"
      ]
    },
    "/$lang/login": {
      "filePath": "$lang.login.tsx"
    },
    "/$lang/": {
      "filePath": "$lang.index.tsx"
    },
    "/_auth/$lang/dashboard": {
      "filePath": "_auth.$lang.dashboard.tsx",
      "parent": "/_auth"
    },
    "/_auth/invoices/$invoiceId": {
      "filePath": "_auth.invoices.$invoiceId.tsx",
      "parent": "/_auth"
    },
    "/_auth/$lang/invoices/": {
      "filePath": "_auth.$lang.invoices.index.tsx",
      "parent": "/_auth"
    }
  }
}
ROUTE_MANIFEST_END */
